name: bot_toast_module
description: "this module is a part of the juneflow project, it provides a bot_toast module for flutter project. bot_toast using toast, in app notification, snack bar, dialog in juneview module."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/bot_toast_module

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  bot_toast:  #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true