name: bot_toast_module
description: "this module is a part of the juneflow project, it provides a bot_toast module for flutter project. bot_toast using toast, in app notification, snack bar, dialog in juneview module."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/bot_toast_module

version: 0.1.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util: ^0.8.19
  bot_toast: ^4.1.3 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true